In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('~/mission_sih/mission_sih/data/nasa_data.csv')

In [3]:
df.head(5)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,23.04102,92.52061,336.69,0.62,0.71,2018-04-01,606,N20,VIIRS,n,2,296.72,6.39,D,0
1,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.01,7.35,D,0
2,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.01,6.89,D,0
3,22.50259,92.55136,330.26,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.59,8.80,D,0
4,22.50408,92.55746,346.15,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,298.87,10.10,D,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5089539 entries, 0 to 5089538
Data columns (total 15 columns):
 #   Column      Dtype
---  ------      -----
 0   latitude    float64
 1   longitude   float64
 2   brightness  float64
 3   scan        float64
 4   track       float64
 5   acq_date    str
 6   acq_time    int64
 7   satellite   str
 8   instrument  str
 9   confidence  str
 10  version     int64
 11  bright_t31  float64
 12  frp         float64
 13  daynight    str
 14  type        int64
dtypes: float64(7), int64(3), str(5)
memory usage: 582.5 MB

In [5]:
df.drop(columns=["satellite","instrument","version"], inplace=True)

In [6]:
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,confidence,bright_t31,frp,daynight,type
0,23.04102,92.52061,336.69,0.62,0.71,2018-04-01,606,n,296.72,6.39,D,0
1,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,n,299.01,7.35,D,0
2,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,n,299.01,6.89,D,0
3,22.50259,92.55136,330.26,0.63,0.72,2018-04-01,606,n,299.59,8.80,D,0
4,22.50408,92.55746,346.15,0.63,0.72,2018-04-01,606,n,298.87,10.10,D,0

In [7]:
df2 = df.replace({"daynight":{"D":0,"N":1}, "confidence":{"l":0,"n":1,"h":2}})

In [8]:
df2["acq_date"] = pd.to_datetime(df2['acq_date'], format='%Y-%m-%d')

In [9]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5089539 entries, 0 to 5089538
Data columns (total 12 columns):
 #   Column      Dtype
---  ------      -----
 0   latitude    float64
 1   longitude   float64
 2   brightness  float64
 3   scan        float64
 4   track       float64
 5   acq_date    datetime64[us]
 6   acq_time    int64
 7   confidence  object
 8   bright_t31  float64
 9   frp         float64
 10  daynight    object
 11  type        int64
dtypes: datetime64[us](1), float64(7), int64(2), object(2)
memory usage: 466.0+ MB

In [ ]:
df2.to_csv('~/mission_sih/mission_sih/data/nasa_data_cleaned.csv', index=False)